blueprint:
  name: 小米电视激活
  description: 小米电视激活通知
  domain: automation
  source_url: https://github.com/shaonianzhentan/xiaomi_tv
  input:
    media_entity:
      name: 电视
      description: 小米电视
      default: []
      selector:
        entity:
          domain: media_player
    tv_on:
      name: 电视打开
      description: 电视打开了，可以操作啦
      default: []
      selector:
        action: {}
trigger:
  - platform: state
    entity_id: !input media_entity
    to: 'on'
action: !input 'tv_on'