blueprint:
  name: 电视开关
  description: 电视开关事件
  domain: automation
  source_url: https://github.com/shaonianzhentan/xiaomi_tv
  input:
    tv_on:
      name: 打开电视
      description: TV ON
      default: []
      selector:
        action: {}
    tv_off:
      name: 关闭电视
      description: TV OFF
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: xiaomi_tv
action:
- variables:
    type: '{{ trigger.event.data.type }}'
- choose:
  - conditions:
    - '{{ type == "on" }}'
    sequence: !input 'tv_on'
  - conditions:
    - '{{ type == "off" }}'
    sequence: !input 'tv_off'